### ISSUE TITLE
onmouseover

### ISSUE THREAD

**Issue by marcojalongo** [object505/tipso#10]
Hello, this is my code:
<pre>
$(document).ready(function(){
	$("div.ajax" ).on( "mouseover", function() {
		$(this).tipso({
			background: null,
			useTitle: false,
			ajaxContentUrl : 'myfile.php?var='+$(this).data("id")
		});
	});
}); 
</pre>
it works but why the tooltip is showed only the second time the mouse is over the div element (with class = ajax)?
Sorry, I'm newbe with jquery...

Thank a lot

**Comment by object505** [comment]
Hello,
You don't need the mouseover event, because tipso is already doing that.
So you just need to do this:

    $(document).ready(function(){        
        $("div.ajax").tipso({
            background: null,
            useTitle: false,
            ajaxContentUrl : 'myfile.php?var='+$(this).data("id")
        });        
    });

**Comment by marcojalongo** [comment]
Ok, but the problem is that I have a lot of <div> with class = ajax; 
how I can't retrieve $this data of specific <div>...?

**Comment by marcojalongo** [comment]
I mean that your code give me var= undefined....

**Comment by object505** [comment]
Oh, I see.
Maybe something like this would help

    var dataID;
    $('div.ajax').on({
      mouseenter: function () {
        dataID = $(this).data('id');
      }
    });
    $("div.ajax").tipso({
        background: null,
        useTitle: false,
        ajaxContentUrl : 'myfile.php?var='+dataID 
    });    

I guess in a future release of the plugin I would have to implement this.
Let me know if this works for you :)

**Comment by marcojalongo** [comment]
it doesn't work... in console log i see "var=undefined" yet

Have you other suggestion?

thanks again...

**Comment by object505** [comment]
Well this works http://jsfiddle.net/1kb064w7/
Another thing is to give me the site url and let me check what is going on :)

**Comment by marcojalongo** [comment]
It's work, but how to apply this example to "ajaxContentUrl" (not static "content") I'm using....? I tried to return from function the url of script (e.g.; return 'myscript.php?var='+dataID') but it doesn't work...

**Comment by marcojalongo** [comment]
sorry... my application is on local server but use exactly same syntax...

**Comment by object505** [comment]
The same code will be used as here https://github.com/object505/tipso/issues/10#issuecomment-92782551

Basically that is the same code as in the jsfiddle. If you can make some test environment somewhere I can help you more :)

**Comment by marcojalongo** [comment]
Ok; I've make following test environment:

1) http://www.giglione.it/appl/mainscript.php

this is your solution (#10 comment); as you can see, ajax request send back "undefined" instead of values "var1", "var2",.... (in console log, too)

2) http://www.giglione.it/appl/mainscript1.php

this is my "dirty" solution; it is ok, but only on second mouse over.

the ajax script for dynamic tip content (myscript.php) actually simply is:

<code>
<?php
echo $_GET['var']
?> 
</code>

**Comment by object505** [comment]
Based on your test environment I've tested this code and it is working.

        jQuery(document).ready(function(){			
			var dataID;
			jQuery('div.ajax').on({
				mouseenter: function () {
					dataID = $(this).data('id');			
				}
			});
			jQuery("div.ajax").tipso({
				useTitle: false,
				ajaxContentUrl: 'myscript.php?var='+dataID,
				onBeforeShow: function(){
		            $('div.ajax').tipso('update', 'ajaxContentUrl', 'myscript.php?var='+dataID);
		        }
			});  			 
		});

Let me know if it's works for you :)

PS: On your "dirty" version it works from the second hover because on the first you are calling the plugin for the first time and also you are calling the plugin for each element individually, not using the class .ajax but the element itself ( using "this" ).

**Comment by marcojalongo** [comment]
Great!
thanks a lot!!
