### ISSUE TITLE
Bug display tooltip

### ISSUE THREAD

**Issue by usb248** [object505/tipso#11]
Hi,

I found a bug.
For example when we show at least one time the tooltip and we update position width update method ( like this, sel.tipso('update','position','top) ). In some cases, example, when we pass from the right position to top position. 

The code :
```javascript
jQuery('.tipso').tipso({
	position: 'right',
	background: '#F62459',
	useTitle: false
});

// Click event to change position
jQuery('.update-tipso-position').on('click', function(e){
		jQuery('.tipso').tipso('update', 'position', 'top');
		e.preventDefault();
});
```
After update the position, there is a bug.
I let you see the bug with the screenshot...
![screenshot](https://cloud.githubusercontent.com/assets/7659927/7180239/2531df00-e440-11e4-849d-2b11b729862b.png)

**Comment by manfe** [comment]
You shouldn't close the issue while don't fix it and if you fix it you must associate with this ticket. To be sure it's fixed and do not let us create another one for the same reason.
