### ISSUE TITLE
(Question) Unclear $.fn initiation 

### ISSUE THREAD

**Issue by ametad** [object505/tipso#16]
Hi Bojan,

Nice plugin you build! I was searching for a good example of the pattern you are using and so I found Tipso.

But this line is not clear for me: https://github.com/object505/tipso/blob/master/src/tipso.js#L504

What is the meaning of the following?

```javascript
if (!(this instanceof $)) {
    $.extend(defaults, options);
}
```

**Comment by object505** [comment]
Hello,
That is used to set the default options globally for all instances of the plugin.
Here is a jsfiddle demonstration of it.
http://jsfiddle.net/object505/1kb064w7/1/

Let me know if this is helpful :)

**Comment by ametad** [comment]
Thank you for your response. It is helpful, yes :) But.. I thought that the custom override of defaults is done here: https://github.com/object505/tipso/blob/master/src/tipso.js#L33
Isn't it?
The specific code at line 504 does check if 'this' is part of jQuery.. right? Or perhaps is this the way you do not have to chain the initiation at an element?

```javascript
$.tipso({
    background: "#000"
});

// NOT necessary 
$(#id).tipso({
    background: "#000"
});
```

It is just that I don't understand and want to learn what is happening.. Thank you for your time!

**Comment by object505** [comment]
It is like this, 
When we have this part
`$.extend({}, defaults, options);`
we are saying to merge the defaults and options, without modifying the defaults. 

And in the second part 
`if (!(this instanceof $)) {
        $.extend(defaults, options);
 }`
we say if this is not a jQuery object ( that is why we call it like this `$.tipso()` ) then merge the defaults and options, modifying the defaults so the new options will be defaults of the plugin.

Hopefully this would clear things more :)

**Comment by ametad** [comment]
Thank you very much! This is helpful. Keep up :+1:
