### ISSUE TITLE
Template engine support and title bars

### ISSUE THREAD

**Issue by auxiliary** [object505/tipso#22]
Hey,

Great work with the plugin. I've made a fork (https://github.com/auxiliary/tipso) and added template engine support and title bars and some other changes for my own needs. If you see any of it needed, let me know and I'll make an individual pull request on the feature. The demo page in the fork has some extra examples for the changes.

**Comment by auxiliary** [comment]
Also corner positions

**Comment by object505** [comment]
Great :+1: 
As soon as I have free time I will check the PR and merge everything.

**Comment by object505** [comment]
Hello,
I've merge the pr and everything works perfectly. Added you as [contributor](https://github.com/object505/tipso#contributors).

Thanks for the great work :)

**Comment by auxiliary** [comment]
Neat. Thanks.
