### ISSUE TITLE
Modify Tooltip

### ISSUE THREAD

**Issue by makseo** [object505/tipso#26]
Hallo, maybe someone can help, please? Thanks!

1. How to modify html of "Tooltip"?

```html
<div class="tipso_bubble">
   <div class="tipso_content"></div>
   <div class="tipso_arrow"></div>
</div>
```

For ex.

```html
<div class="tipso_bubble custom_class">
   <div class="tipso_content"></div>
   <div class="tipso_arrow"></div>
</div>
```

**Comment by object505** [comment]
Currently there is no option to modify the HTML of the tooltip.
You can do it manually in the plugin https://github.com/object505/tipso/blob/master/src/tipso.js#L116
