### ISSUE TITLE
How get object id?

### ISSUE THREAD

**Issue by sersar** [object505/tipso#27]
How get current object id for selected tooltip?

**Comment by object505** [comment]
You can get the object id like this http://jsfiddle.net/5t6fLo8d/2/

    $(".tipso").tipso({
        onBeforeShow: function(e){
    	    alert('Element id is ' + e[0].element.context.id);
        }
    });

**Comment by sersar** [comment]
Thank you! Another question. I'm sorry, I do not know English!
It is necessary to get the value of the attribute. Like that:
<div data-a="aaa" data-b="bbb" class="hover-tipso-tooltip">Hover</div>
<div data-a="ccc" data-b="ddd" class="hover-tipso-tooltip">Hover</div>
<script>
            jQuery('.hover-tipso-tooltip').tipso({
                position: 'top',
                background: '#000',
                useTitle: false,
                width: false,
                maxWidth: 300,
                tooltipHover: true,
                content: function(){
                    var a = 'data attribute from a';
                    var b = 'data attribute from b';
                    return 'Data a is '+a+', data b is '+b;
                }
            });
</script>
How to do it?

**Comment by object505** [comment]
You can do it like this http://jsfiddle.net/object505/wnu2xnvs/

    $(".hover-tipso-tooltip").tipso({
        width: false,
        maxWidth: 300,
        position: "top",
        onBeforeShow: function(e){
            var a = $(e[0].element).data('a');
            var b = $(e[0].element).data('b');
            var content = 'Data a is ' + a + ', data b is ' + b;
            $('.hover-tipso-tooltip').tipso('update', 'content', content);
        }
    });

:)

**Comment by sersar** [comment]
Working! Thank you! 
Add support for mobile devices. I have Samsung Note with stylus and when hover on link tooltip don't show. On click only show.
