### ISSUE TITLE
SyntaxError: function statement requires a name

### ISSUE THREAD

**Issue by imransilvake** [object505/tipso#28]
// Tipso.
	if( jQuery( '.tipso' ).length != 0 ) {
		onBeforeShow: function() {
			if( jQuery( window ).width() >= 1200 ) {
				// Tipso.
				jQuery( '.tipso' ).tipso({
					background: 	'#EDEDED',
					color: 			'#333333',
					width: 			100,
					position: 		'top',
					speed: 			300,
					showArrow: 		false,
					tooltipHover: 	true,
					useTitle: 		false,
				});
				// Hide tipso when click on fa.
				jQuery( '.fa' ).on( 'touchstart click', function() {
					jQuery( '.tipso' ).tipso( 'hide' );
				});
			}
		}
	}

Error: SyntaxError: function statement requires a name
How can i fix this?
I want tipso only for laptops computers having screen width more than 1200px

**Comment by object505** [comment]
First of all this error is not related to tipso.
You are calling the `onBeforeShow` method on nothing, you need to call it on the actual plugin :)
And for help how to do this, just call the plugin if the width is bigger then 1200px like you are already doing just without using the onBeforeShow method. 

     if( jQuery( window ).width() >= 1200 ) {
            // Tipso.
            jQuery( '.tipso' ).tipso({
                background:     '#EDEDED',
                color:          '#333333',
                width:          100,
                position:       'top',
                speed:          300,
                showArrow:      false,
                tooltipHover:   true,
                useTitle:       false,
            });
            // Hide tipso when click on fa.
            jQuery( '.fa' ).on( 'touchstart click', function() {
                jQuery( '.tipso' ).tipso( 'hide' );
            });
        }
