### ISSUE TITLE
Changing the content while the tooltip is active

### ISSUE THREAD

**Issue by homamghassemy** [object505/tipso#3]
Hi
i want to use ajax and it may change the content on the fly but i could not figure out how to do this
can you help

by the way this plugin works great on every other acpect.

**Comment by object505** [comment]
Hello,
Do you want to load ajax content while the tooltip is active?
Maybe you can call the ajax with the onShow callback
    
    $('.tipso').tipso({
        onShow: function(){
            // Your ajax code and on success change the content
            $('.tipso').tipso('update', 'content', 'new ajax content');
        }
    });

Let me know if this is helpful :)
