### ISSUE TITLE
Use tipso after page have been rendered with ajax.

### ISSUE THREAD

**Issue by sophiekovalevsky** [object505/tipso#33]
Hello there!

Thanks for this wonderful tool. I would like to know it's possible to get tipso to work after a ajax render on the same page.

I have a page, in which some content is loaded through ajax, after doing that the tipso didn't work.

Any suggestions?

**Comment by object505** [comment]
Hello,
You will need to call tipso on every ajax call ( on success ).
That will do the trick :)

**Comment by sophiekovalevsky** [comment]
Thank you so much @object505
