### ISSUE TITLE
tooltip close button

### ISSUE THREAD

**Issue by rosivanov** [object505/tipso#35]
Hi Bojan! I try to make close button inside tooltip and using .tipso('hide') but no success. Can you please take a look below and advise what i'm doing wrong.
This is a screenshot for clarifying [http://joxi.ru/4AkZRd0sPbge2q](http://joxi.ru/4AkZRd0sPbge2q)
```
// tipso init
$('.thumbnail').tipso({
  tooltipHover: true,
  ....
});
// .btn-close handler 
$('body').on('click', '.btn-close', function() {
  $('.thumbnail').tipso('hide');
});
```

**Comment by object505** [comment]
Hello,
Can you make a http://jsfiddle.net/ example using you code?

:)

**Comment by rosivanov** [comment]
Sure =) (http://codepen.io/ros/pen/wKxymb)[http://codepen.io/ros/pen/wKxymb]

**Comment by object505** [comment]
Hello,
In the forthcoming weekend I will make an update to the plugin implementing `close` event, so this issue will be fixed then.

:)

**Comment by rosivanov** [comment]
Awesome! Thank you =)
