### ISSUE TITLE
Horizontal positioning 

### ISSUE THREAD

**Issue by MaestroJurko** [object505/tipso#37]
Tooltip is not positioned correctly when:

 tooltip x position + width > window with + scroll position 
 tooltip x position < 0

**Comment by object505** [comment]
Can you make an example using http://jsfiddle.net/ or similar?

**Comment by MaestroJurko** [comment]
Sorry currently I am really busy. Will try to do it as soon as possible.

But the use case is, when a tooltip is opened next to left/right side of window, it is not positioned correctly.

Right (it resizes the window), Left (tooltip is cut off)
