### ISSUE TITLE
Animation tooltip

### ISSUE THREAD

**Issue by usb248** [object505/tipso#4]
Hello, your plugin is very useful but i think that it will be nicest if we can choice other animation (why not use CSS3 animation ... for this moment only fade effect). Many plugin work with several choice of animation in CSS3 and if browser doesn't support CSS3 animation, use alternative jquery method.
So, my question is, have you planned to do this development ?

(I'm french, sorry for my bad english :S)

**Comment by object505** [comment]
Hello,
Thank you for using my plugin.
In the next release of the plugin I will add css3 animation effects for sure. 

:)

**Comment by usb248** [comment]
When is this next release :) ? (when i talked about other plugin, i give you an example http://ned.im/noty/#/about)

**Comment by object505** [comment]
New version 1.0.2 is out.
There are css3 animation effects for showing/hiding the tooltip.
Check it out [here] (http://tipso.object505.com/) :)

**Comment by usb248** [comment]
Oww yes ! Just a question, for checking CSS3 animation support i have seen that you only check if it's IE <= 9 but i don't believe that just IE <= 9 don't support CSS3 animation. Check this [link](http://caniuse.com/#feat=css-animation)
