### ISSUE TITLE
Close Failing when clicking within Tooltip

### ISSUE THREAD

**Issue by brian-schick** [object505/tipso#41]
The new $('.tipso').tipso('close') method fails to do anything for me when I run this directly from a button within the tooltip, the same result also for the alternate syntax listed.

For now, I'm working around this by hiding .tooltip_bubble directly via jQuery, then destroying/reattaching  tipso; this works just fine, but I'd of course prefer to use the API method if possible.

**Comment by object505** [comment]
Hello,
Can you make an example using http://codepen.io/ or https://jsfiddle.net/ ?

Thanks :)
