### ISSUE TITLE
Wrong left and top offset ipad mini 2

### ISSUE THREAD

**Issue by R3dRidle** [object505/tipso#44]
On ipad mini 2 we have an error where the left and top offset are completely wrong:
left: -423112px;
top: 1871px;

Is this a known issue, or is there a fix for this?

All goed well on ipad mini 3.

**Comment by R3dRidle** [comment]
The error somewhere lies in your calculation between lines 829 and 837:

if (pos_left + obj.settings.width > $win.outerWidth() && (obj.settings.position === 'bottom' || obj.settings.position === 'top'))
    {
      diff = $win.outerWidth() - (pos_left + obj.settings.width);
      tipso_bubble.find('.tipso_arrow').css({
        marginLeft: -diff - obj.settings.arrowWidth,
        marginTop: ''
      });
      pos_left = pos_left + diff;
    }

**Comment by object505** [comment]
Hello,
Let me know how are you using the plugin (options, elements etc.), make a jsfiddle or codepen example so I can try to fix the issue.
Also let me know what browser are you using.
I don't have an iPad mini 2 so I can't check what is going on there, so If you can figure out what is causing the problem let me know or make a PR.

:)

**Comment by R3dRidle** [comment]
Well there is something wrong with the calculation on iPad 2.

You could check it on http://www.browserstack.com/ 
Default browser on iPad 2.
