### ISSUE TITLE
show only on click

### ISSUE THREAD

**Issue by vcebotari** [object505/tipso#47]
hi, the tipso tooltip showing on hover , can i set it only on click?

**Comment by object505** [comment]
Hello,
At the moment the only event to show the tooltip is on hover.

There are methods you can use to show/hide the tooltip on click:

```
// Show the tipso tooltip
$('.tipso').tipso('show');

// Hide the tipso tooltip
$('.tipso').tipso('hide');
```

**Comment by otundra** [comment]
This would be a nice one
