### ISSUE TITLE
package.json "main" should just be JS entry point

### ISSUE THREAD

**Issue by isaacs** [object505/tipso#5]
The `main` field in package.json is set up to be an array.  However, this should just be the JavaScript file so that tools like Browserify can know the module's entry point.

It should probably be just `src/tipso.min.js`.  I'm happy to send a PR if you agree.

**Comment by isaacs** [comment]
Note: I'm not sure how this works with bower.json, so it might be 100% ok there.

**Comment by object505** [comment]
Yes you can send a PR, that would be great.
I have little experience with npm, so If you can also test the package I would be very grateful :)
Thanks :+1:

**Comment by object505** [comment]
Merged and updated :)
Thank you :+1:
