### ISSUE TITLE
Ignore mouseover/mouseout?

### ISSUE THREAD

**Issue by remisture** [object505/tipso#62]
Is there a way to show a tooltip "always", until I manually close it? What I mean is, in this case, I don't want the tooltip to show/hide when I hover the connecting element.

**Comment by christian4423** [comment]
http://tipso.object505.com/ I would look into the "Show tipso on page load" example and mix it with the "Interact with tipso tooltip" and the "Click to show/hide tipso" examples.

**Comment by remisture** [comment]
I did something like this:

```
var init = function () {
   var tooltip = $('.tooltip').tipso({
      position: 'bottom',
      content: 'Some content'
   });

   tooltip.tipso('show');
   tooltip.off('mouseover.tipso');
   tooltip.off('mouseout.tipso');
};
```
