### ISSUE TITLE
Cheking support CSS3 animation

### ISSUE THREAD

**Issue by usb248** [object505/tipso#7]
Hi,

 I have seen in your plugin that you check if IE <= 9 to set alternative jquery fade animation but i don't believe [[link](http://caniuse.com/#feat=css-animation)] that just IE <= 9 don't support CSS3 animation...
```javascript
if ( _isIE() <= 9 ) {
this.ieFade = true;
} 
```
It may be an approach [[link](http://stackoverflow.com/questions/7264899/detect-css-transitions-using-javascript-and-without-modernizr)] or maybe look how modernizr check this...

**Comment by object505** [comment]
Hello,
Yes, at the moment the plugin is just checking for CSS3 animation support on ie only.
In the next release I will implement a full check for CSS3 animation support.

:+1:
