### ISSUE TITLE
Change tipso cursor icon

### ISSUE THREAD

**Issue by kaustavbhattacharjee** [object505/tipso#79]
I need to to change the cursor icon when a tipso tooltip is selected. Currently the icon shows up as a question mark like this: `?`

I need to change it to something different, like the normal cursor icon.

**Comment by object505** [comment]
You just need to update the css for the class `tipso_style`, overwrite the style for the cursor

`
    .tipso_style {
         cursor: help;
         border-bottom: 1px dotted;
    }
`
