### ISSUE TITLE
Problem with the minify version

### ISSUE THREAD

**Issue by Aymkdn** [object505/tipso#8]
Hi,

I don't know which minified tool you use, but your file https://raw.githubusercontent.com/object505/tipso/master/src/tipso.min.js returns an error: `TypeError: e.G is undefined`

I minified your code with http://refresh-sf.com/ and this time it worked :-)

**Comment by gerrypower** [comment]
Had the same issue.

**Comment by object505** [comment]
Hello,
The issue is now fixed :)

Thanks :+1:
